<?php
$maxDepth = $this->maxDepth();
$rows = $this->getRow();
//Mage::log($this->getComments());
//Mage::log($this->buildCommentTree());
//Mage::log($rows);
?>
    <!-- <div class="container"> -->
    <div class="control-panel">
        <a href="<?php echo $this->getUrl('*/*/list'); ?>"><button class="btn btn-primary">Back</button></a>
        <button id="saveAllBtn" class="btn btn-success">Save All</button>
        <button class="btn btn-success" id="completedcomments">Show<br>Completed<br>Comments</button>
        <button class="btn btn-success" id="continuecomments">Show<br>Continue<br>Comments</button>
        <!-- <div class="container"> -->
        <input type="number" name="last" id="lastlevel">
        <button type="submit" id="btn-lastlevel" class="btn btn-primary">Show</button>
        <!-- </div> -->
    </div>

    <table class="table-bordered border-dark" id="commentTable">
        <thead id="tableHead">
            <th>Root</th>
            <?php for($i=$this->getStartLevel(); $i<$maxDepth+$this->getStartLevel(); $i++): ?>
            <th>level
                <?php echo $i+1; ?>
            </th>
            <?php endfor; ?>
        </thead>
        <tbody id="qaBody">
            <tr>
                <?php foreach($rows as $key => $value): ?>
                <?php if($value['rowstart'] == 1): ?>
                <tr>
                    <?php endif; ?>
                    <?php $class = $value['is_active'] ? '' : 'border-success border-3 bg-success-subtle' ?>
                    <td rowspan="<?php echo $value['rowspan']; ?>" data-level="<?php echo $value['level']; ?>" data-id="<?php echo $key; ?>" class="position-relative level-<?php echo $value['depth']; ?> <?php echo $class; ?>">
                        <b><?php echo 'Id:' . $key . '<br>level-' . $value['level']; ?></b>

                        <?php if($value['depth']-1 == $maxDepth-1 && $value['depth'] > 1 && $value['is_active']): ?>
                        <button type="button" class="btn btn-success complete position-absolute top-0 end-0 m-1"><i class="bi-check"></i></button>
                        <?php endif; ?>

                        <br>
                        <?php echo $value['comment']; ?>
                    </td>
                    <?php if($value['depth'] == $maxDepth && $value['is_active']): ?>
                    <td class="addComment">
                        <button type="submit" class="add-btn">Add Comment</button>
                    </td>
                    <?php endif; ?>
                    <?php if($value['rowend'] && $value['depth']< $maxDepth): ?>
                    <?php echo str_repeat("<td></td>", $maxDepth-$value['depth']); ?>
                    <?php endif; ?>
                    <?php if($value['rowend'] == 1): ?>
                </tr>
                <?php endif; ?>
                <?php endforeach; ?>
        </tbody>
    </table>
    <!-- </div> -->