<h3>Question Table</h3>

<table id="questionTable">
    <tr>
        <td rowspan="6">Q1
            <button>Add Answer to Q1</button>
        </td>
        <td rowspan="2">A1
            <button>Add Answer</button>
        </td>
        <td>Q1
            <button>Add Answer</button>
        </td>
        <td>1
            <button>Add Answer</button>
        </td>
    </tr>
    <tr>
        <td>Q2 <button>Add Answer</button></td>
        <td>2 <button>Add Answer</button></td>
    </tr>
    <tr>
        <td rowspan="2">A2
            <button>Add Answer</button>
        </td>
        <td rowspan="2">Q3
            <button>Add Answer</button>
        </td>
        <td>3
            <button>Add Answer</button>
        </td>
    </tr>
    <tr>
        <td>4
            <button>Add Answer</button>
        </td>
    </tr>
    <tr>
        <td rowspan="2">A3
            <button>Add Answer</button>
        </td>
        <td rowspan="2">Q4
            <button>Add Answer</button>
        </td>
        <td>5
            <button>Add Answer</button>
        </td>
    </tr>
    <tr>
        <td>6
            <button>Add Answer</button>
        </td>
    </tr>
</table>

<button onclick="submitAnswers()">Submit</button>