<?php
$billData = $this->getBillingData();
$shipData = $this->getShippingData();
?>

    <div class="container">
        <h1 class="page-title">Checkout</h1>

        <div class="checkout-container">
            <!-- Left Column: Forms -->
            <div class="checkout-forms">
                <!-- Order Summary (Mobile Only) -->

                <form id="billing-form" class="trigger-on-submit" action="<?php echo $this->getUrl('*/*/save') ?>" method="post">
                    <!-- Customer Information -->
                    <div class="checkout-section">
                        <h3 class="section-title">Customer Information</h3>
                        <div class="form-row">
                            <div class="form-group">
                                <label for="email">Email Address*</label>
                                <input type="email" class="validate_require validate_email" id="email" name="customer_email" value="<?= $this->getEmail() ?>">
                                <!-- <span id="email-error"></span> -->
                            </div>

                        </div>
                    </div>

                    <!-- Billing Address -->
                    <div class="checkout-section">
                        <h3 class="section-title">Billing Address</h3>

                        <div class="form-row">
                            <input type="hidden" id="billing_id" name="billing[address_id]" value="<?= $billData->getAddressId(); ?>">
                            <div class="form-group">
                                <label for="billing_firstname">First Name*</label>
                                <input type="text" class="validate_require validate_name" id="billing_firstname" name="billing[firstname]" value="<?= $billData->getFirstname() ?>">
                                <!-- <span id="billing-fname-error"></span> -->
                            </div>
                            <div class="form-group">
                                <label for="billing_lastname">Last Name*</label>
                                <input type="text" class="validate_require validate_name" id="billing_lastname" name="billing[lastname]" value="<?= $billData->getLastname() ?>">
                                <!-- <span id="billing-lastname-error"></span> -->
                            </div>
                            <div class="form-group">
                                <label for="phone">Phone Number*</label>
                                <input type="tel" class="validate_require validate_phone" id="billing_phone" name="billing[phone]" value="<?= $billData->getPhone() ?>">
                                <!-- <span id="billing-phone-error"></span> -->
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="billing_address1">Street Address</label>
                            <input type="text" class="validate_require validate_address" id="billing_address1" name="billing[street_address]" value="<?= $billData->getStreetAddress() ?>">
                            <!-- <span id="billing-address-error"></span> -->
                        </div>

                        <div class="form-row">
                            <div class="form-group">
                                <label for="billing_city">City*</label>
                                <input type="text" class="validate_require validate_name" id="billing_city" name="billing[city]" value="<?= $billData->getCity() ?>">
                                <!-- <span id="billing-city-error"></span> -->
                            </div>
                            <div class="form-group">
                                <label for="billing_state">State*</label>
                                <input type="text" class="validate_require validate_name" id="billing_state" name="billing[region]" value="<?= $billData->getRegion() ?>">
                                <!-- <span id="billing-state-error"></span> -->
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group">
                                <label for="billing_country">Country*</label>
                                <input type="text" class="validate_require validate_name" id="billing_country" name="billing[country]" value="<?= $billData->getCountry() ?>">
                                <!-- <span id="billing-country-error"></span> -->
                            </div>
                            <div class="form-group">
                                <label for="billing_zip">Zip Code*</label>
                                <input type="text" class="validate_require validate_zipcode" id="billing_zip" name="billing[zipcode]" value="<?= $billData->getZipcode() ?>">
                                <!-- <span id="billing-zipcode-error"></span> -->
                            </div>
                        </div>
                        <input type="hidden" name="billing[address_type]" value="billing">
                    </div>

                    <!-- Shipping Address -->
                    <div class="checkout-section">
                        <h3 class="section-title">Shipping Address</h3>
                        <div class="same-address-checkbox">
                            <input type="checkbox" id="same_as_billing" name="shipping2[same_as_billing]">
                            <label for="same_as_billing">Same as billing address</label>
                        </div>

                        <input type="hidden" id="billing_id" name="shipping[address_id]" value="<?= $shipData->getAddressId(); ?>">
                        <div class="form-row">
                            <div class="form-group">
                                <label for="shipping_firstname">First Name*</label>
                                <input type="text" class="validate_require validate_name" id="shipping_firstname" name="shipping[firstname]" value="<?= $shipData->getFirstname(); ?>">
                                <!-- <span id="shipping-fname-error"></span> -->
                            </div>
                            <div class="form-group">
                                <label for="shipping_lastname">Last Name*</label>
                                <input type="text" class="validate_require validate_name" id="shipping_lastname" name="shipping[lastname]" value="<?= $shipData->getLastname(); ?>">
                                <!-- <span id="shipping-lastname-error"></span> -->
                            </div>
                            <div class="form-group">
                                <label for="phone">Phone Number*</label>
                                <input type="tel" class="validate_require validate_phone" id="shipping_phone" name="shipping[phone]" value="<?= $shipData->getPhone(); ?>">
                                <!-- <span id="shipping-phone-error"></span> -->
                            </div>
                        </div>

                        <div class="form-group">
                            <label for="shipping_address1">Street Address</label>
                            <input type="text" class="validate_require validate_address" id="shipping_address1" name="shipping[street_address]" value="<?= $shipData->getStreetAddress() ?>">
                            <!-- <span id="shipping-address-error"></span> -->
                        </div>

                        <div class="form-row">
                            <div class="form-group">
                                <label for="shipping_city">City*</label>
                                <input type="text" class="validate_require validate_name" id="shipping_city" name="shipping[city]" value="<?= $shipData->getCity() ?>">
                                <!-- <span id="shipping-city-error"></span> -->
                            </div>
                            <div class="form-group">
                                <label for="shipping_state">State*</label>
                                <input type="text" class="validate_require validate_name" id="shipping_state" name="shipping[region]" value="<?= $shipData->getRegion() ?>">
                                <!-- <span id="shipping-state-error"></span> -->
                            </div>
                        </div>

                        <div class="form-row">
                            <div class="form-group">
                                <label for="shipping_country">Country*</label>
                                <input type="text" class="validate_require validate_name" id="shipping_country" name="shipping[country]" value="<?= $shipData->getCountry() ?>">
                                <!-- <span id="shipping-country-error"></span> -->
                            </div>
                            <div class="form-group">
                                <label for="shipping_zip">Zip Code*</label>
                                <input type="text" class="validate_require validate_zipcode" id="shipping_zip" name="shipping[zipcode]" value="<?= $shipData->getZipcode() ?>">
                                <!-- <span id="shipping-zipcode-error"></span> -->
                            </div>
                        </div>
                        <input type="hidden" name="shipping[address_type]" value="shipping">
                        <button type="submit" class="place-order-btn">Save Address</button>
                </form>
                </div>
            </div>
        </div>