<?php $products = $this->getProductData(); ?>
<div class="col-md-9" id="productContainer">
    <?php $this->getChildHtml('toolbar'); ?>

    <h3>Products</h3>
    <div class="row">
        <!-- <div class="row" id="productContainer"> -->
        <?php if(!empty($products)): ?>
        <?php foreach ($products as $product): ?>
        <div class="col-md-4 mb-4 product-card" data-price="<?= $product->getPrice(); ?>">
            <div class="card">
                <img src="http://localhost/mvcproject/<?= $product->getFilePath(); ?>" class="card-img-top" alt="<?= $product->getName(); ?>">
                <div class="card-body">
                    <h5 class="card-title">
                        <?= substr($product->getName(), 0, 25); ?>
                    </h5>
                    <p class="card-text">
                        <?= substr($product->getDescription(), 0, 50); ?>...</p>
                    <p class="text-primary fw-bold">₹
                        <?= $product->getPrice(); ?>
                    </p>
                    <a href="<?= $this->getUrl('*/*/view').'/?product_id='.$product->getProductId(); ?>" class="btn btn-primary">View Details</a>
                </div>
            </div>
        </div>
        <?php endforeach; ?>
        <?php else: ?>
        <p>No products found.</p>
        <?php endif; ?>
    </div>
</div>