<div>
<?php $this->getEvents(); ?>
    <?php $this->getChildHtml('toolbar'); ?>
    <a class="btn btn-primary" href="<?php echo $this->getUrl('*/*/new') ?>">add Event</a>
    <table id="grid-data">
        <thead>
            <tr>
                <th>Event_Id</th>
                <th>Title</th>
                <th>Description</th>
                <th>Date</th>
                <th>Location</th>
                <th>Capacity</th>
                <th>Created_By</th>
                <th>Created_At</th>
                <th>Total Registration</th>
                <th>Edit</th>
                <th>Delete</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach($this->getEvents() as $event):  ?>
            <tr>
                <td>
                    <?= $event->getEventId() ?>
                </td>
                <td>
                    <?= $event->getTitle() ?>
                </td>
                <td>
                    <?= $event->getDescription() ?>
                </td>
                <td>
                    <?= $event->getDate() ?>
                </td>
                <td>
                    <?= $event->getLocation() ?>
                </td>
                <td>
                    <?= $event->getCapacity() ?>
                </td>
                <td>
                    <?= $event->getCreatedBy() ?>
                </td>
                <td>
                    <?= $event->getCreatedDate() ?>
                </td>
                <td>
                    <a href="<?= $this->getUrl('*/*/view') ?>/?event_id=<?= $event->getEventId(); ?>" class="btn edit-btn">View Registration(<?= $event->getTotal(); ?>)</a>
                </td>
                <td>
                    <a href="<?= $this->getUrl('*/*/new') ?>/?edit_id=<?= $event->getEventId(); ?>" class="btn edit-btn">Edit</a>

                </td>

                <td>
                    <a href="<?= $this->getUrl('*/*/delete') ?>/?delete_id=<?= $event->getEventId(); ?>" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this record?');">
                        Delete
                    </a>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>