<?php $data = $this->getEvents(); ?>

<div>
    <form action="<?= $this->getUrl('*/*/save') ?>" method="post">
        <input type="hidden" name="event[event_id]" value="<?= $data->getEventId(); ?>">
        <div class="form-group">
            <label>Title:</label>
            <input type="text" name="event[title]" value="<?= $data->getTitle(); ?>">
        </div>
        <div class="form-group">
            <label>Description:</label>
            <textarea name="event[description]"><?= $data->getDescription(); ?></textarea>
        </div>
        <div class="form-group">
            <label>date:</label>
            <input type="date" name="event[date]" value="<?= $data->getDate(); ?>" min="<?php //echo Date('Y-m-d'); ?>">
        </div>
        <div class="form-group">
            <label>Location:</label>
            <input type="text" name="event[location]" value="<?= $data->getLocation(); ?>">
        </div>
        <div class="form-group">
            <label>Capacity:</label>
            <input type="number" name="event[capacity]" value="<?= $data->getCapacity(); ?>">
        </div>
        <button type="submit" class="btn btn-primary">Save Event</button>
    </form>
</div>