<h2 class="text-center">Category List</h2>

<div class="table-container">
    <div class="d-flex justify-content-end mb-3">
        <a class="btn btn-primary" href="<?php echo $this->getUrl('*/*/new') ?>">add category</a>
    </div>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th>Parent Category Id</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php $categories = $this->getCategoriesData(); ?>
            <?php foreach ($categories as $catdata): ?>
            <tr>
                <td>
                    <?php echo ($catdata->getCategoryId()); ?>
                </td>
                <td>
                    <?php echo ($catdata->getName()); ?>
                </td>
                <td>
                    <?php echo ($catdata->getDescription()); ?>
                </td>
                <td>
                    <?php echo ($catdata->getParentId()); ?>
                </td>
                <td>
                    <!-- Edit Link -->
                    <a href="<?= $this->getUrl('*/*/new') ?>/?edit_id=<?= $catdata->getCategoryId(); ?>" class="btn edit-btn">Edit</a>

                    <!-- Delete Link with Confirmation -->
                    <a href="<?= $this->getUrl('*/*/delete') ?>/?delete_id=<?= $catdata->getCategoryId(); ?>" class="btn btn-danger" onclick="return confirm('Are you sure you want to delete this record?');">
                        Delete
                    </a>

                </td>
            </tr>
            <?php endforeach ?>

        </tbody>
    </table>
</div>