<?php
    $data = $this->getroductsData();
?>


    <h2>All Product</h2>
    <div class="col-md-2">
        <a class="add-new" href="<?php echo $this->getUrl('*/*/new') ?>">add product</a>
    </div>
    <?php if (count($data) > 0): ?>
    <table>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Category</th>
            <th>Description</th>
            <th>Price</th>
            <th>Image</th>
            <th>Color</th>
            <th>Size</th>
            <th>Brand</th>
            <th>Made_In</th>
            <th>Model</th>
            <th>Mfg_Date</th>
            <th>Material</th>
            <th>Status</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>

        <?php foreach ($data as $pro):
    ?>
        <tr>
            <td>
                <?php echo $pro->getProductId(); ?>
            </td>
            <td>
                <?php echo $pro->getName(); ?>
            </td>
            <td>
                <?php echo $pro->getCategoryName(); ?>
            </td>
            <td>
                <?php echo $pro->getDescription(); ?>
            </td>
            <td>
                <?php echo $pro->getPrice(); ?>
            </td>
            <td>
                <img src="<?php echo Mage::getBaseUrl().$pro->getImage(); ?>" alt="Product Image" width="100" height="100" style="border-radius: 5px;">
                <!-- <?php //echo $pro->getImage(); ?> -->
            </td>
            <td>
                <div id="colordiv" style="background-color:<?php echo $pro->getColor(); ?>;">    
                </div>
                <?php echo $pro->getColor(); ?>
            </td>
            <td>
                <?php echo $pro->getSize(); ?>
            </td>
            <td>
                <?php echo $pro->getBrand(); ?>
            </td>
            <td>
                <?php echo $pro->getMadeIn(); ?>
            </td>
            <td>
                <?php echo $pro->getModel(); ?>
            </td>
            </td>
            <td>
                <?php echo $pro->getMfgDate(); ?>
            </td>
            <td>
                <?php echo $pro->getMaterial(); ?>
            </td>
            <td>
                <?php echo ($pro->getStatusText()) ?>
            </td>
            <td>
                <a href='New/?id=<?php echo $pro->getProductId(); ?>'> <i class='fa fa-edit' style="color:blue;"></i></a>
            </td>
            <td>
                <a href='Delete/?id=<?php echo $pro->getProductId(); ?>' onclick="return confirm('Are you sure you want to delete this record?')"> <i class='fas fa-trash' style="color:red;"></i></a>
            </td>
        </tr>
        <?php endforeach; ?>
    </table>
    <?php else: ?>
    <p>No Product available. </p>
    <?php endif; ?>