<footer class="bg-dark text-white text-center py-1 position-relative">
    <div class="container">
        <!-- Social Media Icons -->
        <div class="d-flex justify-content-center gap-3 mb-2">
            <a href="#" class="text-white"><i class="bi bi-facebook fs-4"></i></a>
            <a href="#" class="text-white"><i class="bi bi-twitter-x fs-4"></i></a>
            <a href="#" class="text-white"><i class="bi bi-instagram fs-4"></i></a>
            <a href="#" class="text-white"><i class="bi bi-youtube fs-4"></i></a>
        </div>

        <!-- Copyright Text -->
        <p class="mb-0">&copy; 2025 Yash Patel. All rights reserved.</p>
    </div>

    <!-- Back to Top Button -->
    <!-- <a href="#" id="backToTop" class="btn btn-dark position-absolute end-0 bottom-0 m-3"> -->
    <a href="#" id="backToTop" class="btn btn-dark position-absolute end-0 bottom-0 m-3">
        <i class="bi bi-arrow-up-short fs-3"></i>
    </a>
</footer>