<head>
    <?php foreach ($this->getJs() as $jsfile): ?>
    <script src="<?php echo Mage::getBaseUrl().'js/'.$jsfile; ?>">
    </script>
    <?php endforeach; ?>

    <?php foreach ($this->getCss() as $cssfile): ?>
    <link rel="stylesheet" href="<?php echo Mage::getBaseUrl().'css/'.$cssfile; ?>">
    <?php endforeach; ?>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

</head>